# Generated by Django 4.2.2 on 2023-06-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificationsApp', '0002_alter_certificate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='id_type',
            field=models.CharField(default='C.C', max_length=10, verbose_name='id_type'),
            preserve_default=False,
        ),
    ]
